import {
  API_KEY_SUPABASE,
  AUTHORIZATION_SUPABASE,
  URL_SUPABASE,
  ENCRYPTION_KEY,
} from '@env';

export const SUPABASE = {
  URL: URL_SUPABASE,
  API_KEY: API_KEY_SUPABASE,
  AUTHORIZATION: AUTHORIZATION_SUPABASE,
};
export const ENCRYP_KEY = ENCRYPTION_KEY;
